[build]
cmd = "pnpm install --ignore-scripts && DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy pnpm run prisma-generate && pnpm run build"

[deploy]
startCommand = "pnpm run pm2"
healthcheckPath = "/"
healthcheckTimeout = 300

[phases.setup]
nixPkgs = ['nodejs', 'python3']
aptPkgs = ['build-essential', 'libudev-dev']