[build]
cmd = "pnpm install && pnpm run build"

[deploy]
startCommand = "pnpm run pm2"
healthcheckPath = "/"
healthcheckTimeout = 300

[phases.setup]
nixPkgs = ['nodejs', 'python3']
aptPkgs = ['build-essential', 'libudev-dev']